version: "3"
services:
  mysqldb:
    image: mysql
    restart: on-failure:2
#    volumes:
#      - /var/lib/mysql # Mount a host directory to persist the MySQL data
    environment:
      MYSQL_DATABASE: test1
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306" # Expose MySQL container's port to host (optional)
    networks:
      - project1
  springbootapp:
    build: . # Build the Spring Boot app using the Dockerfile in the current directory
    restart: on-failure:2
    ports:
      - "8080:8080" # Expose Spring Boot app's port to host
    environment:
      MYSQL_HOST: mysqldb # Set the hostname of the MySQL container
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
#    volumes:
#      - /var/lib/mysql # Mount the same host directory as mysqldb service (optional)
    networks:
      - project1
    depends_on:
      - mysqldb
networks:
  project1: # Define a custom Docker network

           